# Combine files and upload it as zip to the release
# Original file from https://github.com/hacs/integration/blob/main/.github/workflows/release.yml

name: Release

on:
  release:
    types: [published]
    
permissions:
  contents: write

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: "Set version number"
        run: |
          python3 ${{ github.workspace }}/.github/helpers/update_manifest.py --version ${GITHUB_REF##*/}

      - name: Combine ZIP
        run: |
          cd ${{ github.workspace }}/custom_components/flitsmeister
          zip flitsmeister.zip -r ./

      - name: Upload Release Asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/flitsmeister/flitsmeister.zip
          asset_name: flitsmeister.zip
